package com.ecarx.xui.adaptapi.ota;

import java.util.Calendar;
import java.util.List;

public interface IOtaSession {
    int getOtaMode();
    int getOtaType();
    boolean isInstallationStarted();
    boolean couldBeginInstallRightNow();
    boolean isRecoveryOta();
    int getOtaProgress();
    int getOtaPriority();
    boolean ifSystemWillRebootAfterOta();
    boolean cancel();
    boolean download();
    boolean download(String uuid);
    boolean checkUpdate();
    String getCurrentCarVersionName();
    String getSysBssId();
    int getSysVersionCode();
    String getSysVersionName();
    int getOtaBaseSysVersionCode();
    String getOtaBaseSysVersionName();
    boolean setOtaUpdateTime(Calendar calendar);
    Calendar getOtaUpdateTime();
    void requestOtaUpdateTime();
    int getEstimatedInstallationTime();
    boolean cancelOtaUpgradeTime();
    String getUpgradeInfo();
    boolean setPowerState(int i);
    int getOtaUpdateInProgressState();
    boolean isPopupEnable();
    void setInstallRegretState(int i);
    List<Integer> getInstallationtimes();
    String getUUID();
    List<String> getFileNames();
    List<String> getSoftwareSignature();
    String getSignatureCertificate();
    List<String> getDownloadUrls();
    int getTotalSize();
    void checkConnectivityStatus();
    void setOTADownloadStatus(int i, int i1);
    void setOTADownloadSize(int i);
    void reportDownloadFailedName(String s);
    boolean checkSceneModeAlive();
    void setOtaUserSettings(boolean b, boolean b1, boolean b2, boolean b3);
    boolean getOtaSetting();
    boolean getOtaAutoSync();
    boolean getOtaAutoDownload();
    boolean getOtaAutoInstallation();
    void sendUserDownloadRequest(String s, String s1, String s2);
    void sendUserDownloadCancel();
    void sendUserDownloadSuspend();
    void sendUserDownloadResume();
    void sendVbfDecryptionKey(List<OTA.DecryptionKeyType> list);
    void sendBSSIDDisplayedVersionInfo(String s, String s1);
    void changeSlot();
    void requestCurrentCarVersionName();
}