#############################################################################
# Row1LeftMassageRunnable - Updates row1 left massage button
#
# This Runnable is posted to the UI thread when massage level or supported
# observable changes. It calls AcPanelController.updateRow1LeftMassage()
# which updates both enabled state and level display.
#
# Triggered by: onPropertyChanged() when row1LeftMassageLevelObservable
#               or row1LeftMassageSupportedObservable changes
# Thread: Posted to main UI thread via View.post()
#############################################################################

.class Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row1LeftMassageRunnable;
.super Ljava/lang/Object;
.source "AirConditionViewHolder.java"

# interfaces
# Implements Runnable to be executed via View.post()
.implements Ljava/lang/Runnable;

# annotations
# Inner class of AcPanelController
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x0
    name = "Row1LeftMassageRunnable"
.end annotation


#############################################################################
# INSTANCE FIELDS
#############################################################################

# Reference to outer AcPanelController instance
# Synthetic field generated by compiler for inner class access
.field final synthetic this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;


#############################################################################
# CONSTRUCTOR
#############################################################################

# Constructor - stores reference to enclosing AcPanelController
# 
# Parameters:
#   p1 - the enclosing AcPanelController instance (this$0)
.method constructor <init>(Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;)V
    .locals 0

    # Store reference to outer class (required for synthetic field)
    iput-object p1, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row1LeftMassageRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call Object constructor
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


#############################################################################
# RUNNABLE IMPLEMENTATION
#############################################################################

# run - Called on UI thread when posted via View.post()
#
# Delegates to AcPanelController.updateRow1LeftMassage() which
# updates the massage button's enabled state and level display.
.method public run()V
    .locals 1

    # Get reference to enclosing AcPanelController
    iget-object v0, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row1LeftMassageRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call updateRow1LeftMassage() to update the button
    invoke-virtual {v0}, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;->updateRow1LeftMassage()V

    return-void
.end method
