#############################################################################
# Row2RightRunnable - Updates RIGHT rear seat heat button only
#
# This Runnable is posted to the UI thread when row2RightLevelObservable or
# row2RightSupportedObservable changes.
# It calls AcPanelController.updateRow2Right() which:
# - Updates the enabled/disabled state of the RIGHT rear seat heat button
# - Updates the level display (only if enabled)
# - Does NOT affect the LEFT rear seat heat button
#
# IMPORTANT: This Runnable is separate from Row2LeftRunnable to allow
# independent updates for left and right rear seats. When a rear passenger
# activates their seat heat from the rear console, only their button should
# animate - not both buttons.
#
# Triggered by: onPropertyChanged() when row2RightLevelObservable or
#               row2RightSupportedObservable changes
# Thread: Posted to main UI thread via View.post()
#############################################################################

.class Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row2RightRunnable;
.super Ljava/lang/Object;
.source "AirConditionViewHolder.java"

# interfaces
# Implements Runnable to be executed via View.post()
.implements Ljava/lang/Runnable;

# annotations
# Inner class of AcPanelController
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x0
    name = "Row2RightRunnable"
.end annotation


#############################################################################
# INSTANCE FIELDS
#############################################################################

# Reference to outer AcPanelController instance
# Synthetic field generated by compiler for inner class access
.field final synthetic this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;


#############################################################################
# CONSTRUCTOR
#############################################################################

# Constructor - stores reference to enclosing AcPanelController
# 
# Parameters:
#   p1 - the enclosing AcPanelController instance (this$0)
.method constructor <init>(Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;)V
    .locals 0

    # Store reference to outer class (required for synthetic field)
    iput-object p1, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row2RightRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call Object constructor
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


#############################################################################
# RUNNABLE IMPLEMENTATION
#############################################################################

# run - Called on UI thread when posted via View.post()
#
# Delegates to AcPanelController.updateRow2Right() which updates only the
# RIGHT rear seat heat button (enabled state + level).
# This ensures independent animation for left and right rear seats.
.method public run()V
    .locals 1

    # Get reference to enclosing AcPanelController
    iget-object v0, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$Row2RightRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call updateRow2Right() to update only the RIGHT rear seat button
    invoke-virtual {v0}, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;->updateRow2Right()V

    return-void
.end method

