#############################################################################
# ContainerRunnable - Updates visibility of all AC panel elements
#
# This Runnable is posted to the UI thread when acPanelFrontObservable changes.
# It calls AcPanelController.updateContainerVisibility() which:
# - If front panel (acPanelFront = true):
#   - Shows steering wheel, row1 seats (VISIBLE)
#   - Hides row2 seats (GONE)
# - If back panel (acPanelFront = false):
#   - Hides steering wheel, row1 seats (GONE)
#   - Shows row2 seats (VISIBLE)
#
# Triggered by: onPropertyChanged() when acPanelFrontObservable changes
# Thread: Posted to main UI thread via View.post()
#############################################################################

.class Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$ContainerRunnable;
.super Ljava/lang/Object;
.source "AirConditionViewHolder.java"

# interfaces
# Implements Runnable to be executed via View.post()
.implements Ljava/lang/Runnable;

# annotations
# Inner class of AcPanelController
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x0
    name = "ContainerRunnable"
.end annotation


#############################################################################
# INSTANCE FIELDS
#############################################################################

# Reference to outer AcPanelController instance
# Synthetic field generated by compiler for inner class access
.field final synthetic this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;


#############################################################################
# CONSTRUCTOR
#############################################################################

# Constructor - stores reference to enclosing AcPanelController
# 
# Parameters:
#   p1 - the enclosing AcPanelController instance (this$0)
.method constructor <init>(Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;)V
    .locals 0

    # Store reference to outer class (required for synthetic field)
    iput-object p1, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$ContainerRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call Object constructor
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


#############################################################################
# RUNNABLE IMPLEMENTATION
#############################################################################

# run - Called on UI thread when posted via View.post()
#
# Delegates to AcPanelController.updateContainerVisibility() which
# updates the visibility of all seat elements based on front/back panel state.
.method public run()V
    .locals 1

    # Get reference to enclosing AcPanelController
    iget-object v0, p0, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController$ContainerRunnable;->this$0:Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;

    # Call updateContainerVisibility() to update all element visibility
    invoke-virtual {v0}, Lcom/geely/hvac/adapter/AirConditionViewHolder$AcPanelController;->updateContainerVisibility()V

    return-void
.end method

